name: Auto Reload BIND Config

on:
  push:
    branches: [main]

jobs:
  reload-bind:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Serial and Reload BIND
        run: |
          sudo /etc/bind/scripts/update_serial.sh
          sudo systemctl reload bind9
