name: Update BIND Zones

on:
  push:
    branches:
      - main

jobs:
  update-dns:
    runs-on: self-hosted  # Your runner on ns1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run DNS Serial Update Script
        run: |
          sudo /bin/bash /etc/bind/scripts/update_serial.sh
